nohup: ignoring input
training sences: 30
Sence 0 is loaded. scene01.mat
Sence 1 is loaded. scene02.mat
Sence 2 is loaded. scene03.mat
Sence 3 is loaded. scene04.mat
Sence 4 is loaded. scene05.mat
Sence 5 is loaded. scene06.mat
Sence 6 is loaded. scene07.mat
Sence 7 is loaded. scene08.mat
Sence 8 is loaded. scene09.mat
Sence 9 is loaded. scene10.mat
Sence 10 is loaded. scene11.mat
Sence 11 is loaded. scene12.mat
Sence 12 is loaded. scene13.mat
Sence 13 is loaded. scene14.mat
Sence 14 is loaded. scene15.mat
Sence 15 is loaded. scene16.mat
Sence 16 is loaded. scene17.mat
Sence 17 is loaded. scene18.mat
Sence 18 is loaded. scene19.mat
Sence 19 is loaded. scene20.mat
Sence 20 is loaded. scene21.mat
Sence 21 is loaded. scene22.mat
Sence 22 is loaded. scene23.mat
Sence 23 is loaded. scene24.mat
Sence 24 is loaded. scene25.mat
Sence 25 is loaded. scene26.mat
Sence 26 is loaded. scene27.mat
Sence 27 is loaded. scene28.mat
Sence 28 is loaded. scene29.mat
Sence 29 is loaded. scene30.mat
0 (256, 256, 28) 0.91325766 0.004317734
1 (256, 256, 28) 0.6268645 0.0024493488
2 (256, 256, 28) 0.7478274 0.0038342373
3 (256, 256, 28) 0.8852826 0.0023525485
4 (256, 256, 28) 0.90493804 0.0034019176
5 (256, 256, 28) 1.0582489 0.000809521
6 (256, 256, 28) 0.5335211 0.008445868
7 (256, 256, 28) 1.0526695 0.0
8 (256, 256, 28) 0.8439114 0.0029929152
9 (256, 256, 28) 0.93364686 0.0029743377
2024-06-08 20:32:03,459 - INFO: Learning rate:0.0004, batch_size:5.

/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "main.py", line 123, in <module>
    main(learning_rate)
  File "main.py", line 108, in main
    train(epoch, learning_rate, logger)
  File "main.py", line 52, in train
    model_out = model(y, Phi_batch, Phi_s_batch)
  File "/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qqshen/lowrankProject/GAP-net/Spectral_SCI/GAPnet_v1/models_v4.py", line 142, in forward
    x = self.relu(x)
  File "/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    main(learning_rate)    
  File "main.py", line 108, in main
    train(epoch, learning_rate, logger)
  File "main.py", line 57, in train
    Loss.backward()
  File "/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/qqshen/anaconda3/envs/sdnet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 28, 256, 310]], which is output 0 of ReluBackward0, is at version 28; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
